# ----
# Site

title: MusicBot
description: The documentation for the original MusicBot for Discord.
url: https://Just-Some-Bots.github.io/MusicBot
logo: 'images/logo.png'
google_analytics_key: UA-61418431-2
permalink: pretty

collections:
  installation:
    title: Installation
    position: 1
  guides:
    title: Guides
    position: 2

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
