collections:
  documentation:
    title: Documentation
    render: true
  api:
    title: APIs
    render: true
main_links:
  -
    title: 1st layout
    link: /index.html
  -
    title: 2nd layout
    link: /index2.html
  -
    title: 3rd layout
    link: /index3.html
