# ----
# Site

title: MusicBot
description: The documentation for the original MusicBot for Discord.
url: https://Just-Some-Bots.github.io/
baseurl: "/MusicBot"
google_analytics_key:
permalink: pretty

collections:
  installation:
    title: Installation
    position: 1
  guides:
    title: Guides
    position: 2

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

types:
  - get
  - put
  - delete
  - post
